Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -21,4 +21,9 @@ jobs:
         python-version: 3.8  # Version de Python à utiliser
 
     - name: Exécuter les tests
-      run: python -m unittest discover -v
+      run: |
+        if ! python -m unittest discover -v; then
+          git reset --hard HEAD@{1}  # Revert to the state before the failed commit
+          git switch -c failures/$(date +%s)  # Create a new branch with a unique name
+          git push origin HEAD -u  # Push the new branch to remote
+        fi
